server:
  port: 8591
dubbo:
  application:
    name: user-service-provider
  registry:
    address: 172.19.155.20:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
spring:
  datasource:
    url: jdbc:mysql://172.19.155.20:8066/MESSAGEDB?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: user1
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  rabbitmq:
#    port: 5672
#    host: 172.19.155.20
#    username: guest
#    password: guest
#    virtual-host: mycat