server:
  port: 8580
spring:
  datasource:
    url: jdbc:mysql://192.168.10.100:8066/MESSAGEDB?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: user1
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    port: 5672
    host: 192.168.10.100
    username: guest
    password: guest
    virtual-host: mycat
